name: Gait_Analysis
channels:
  - opensim-org
  - conda-forge
  - defaults
dependencies:
  - pip=22.3.1
  - python=3.8.15
  - conda=22.11.1
  #- numpy=1.21.6
  - btk
  - opensim
  - pip:
      - pycgm2